const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../app/[map]/topojson/starwars.json');
fs.readFile(filePath, 'utf8', (err, data) => {
  if (err) {
    console.error('Error reading the file:', err);
    return;
  }

  let topojson;
  try {
    topojson = JSON.parse(data);
  } catch (parseErr) {
    console.error('Error parsing JSON:', parseErr);
    return;
  }

  // TERRITORY
  // give type sector and a name
  topojson.objects.territory.geometries.forEach(({ properties }) => {
    properties.type = 'sector';
  });

  topojson.objects.territory.geometries.forEach(({ properties }) => {
    if (properties.sector) {
      properties.name = properties.sector;
    }
  })

  // Add faction property based on the sector
  topojson.objects.territory.geometries.forEach(({ properties }) => {
    factionSectors.forEach(faction => {
      if (faction.sectors.includes(properties.sector)) {
        properties.faction = faction.factionName.toLowerCase();
      }
    })
  })

  // GUIDES
  // give type hyperspace and a name
  topojson.objects.guide.geometries.forEach(({ properties }) => {
    properties.type = 'hyperspace'
  })
  topojson.objects.guide.geometries.forEach(({ properties }) => {
    if (properties.hyperspace) {
      properties.name = properties.hyperspace
    } else {
      properties.name = `lane ${properties.hid ? properties.hid : '0'} ${properties.cartodb_id ? properties.cartodb_id : '0'}`

    }
  })

  // LOCATION
  // give type hyperspace and a name
  topojson.objects.location.geometries.forEach(({ properties }) => {
    if (!properties.type) {
      properties.type = 'terrestrial'
    }
  })
  // bro, if it doesn't even have a name why bother, just delete it
  topojson.objects.location.geometries = topojson.objects.location.geometries.filter(({ properties }) => properties.name);
  // topojson.objects.location.geometries.forEach(({ properties }) => {
  //   if (!properties.name) {
  //     // TODO: should delete
  //   }
  // });



  // write
  fs.writeFile(filePath, JSON.stringify(topojson, null, 2), 'utf8', (writeErr) => {
    if (writeErr) {
      console.error('Error writing the file:', writeErr);
    } else {
      console.log('File successfully updated.');
    }
  });
});

// https://github.com/jennygrahamjones/galaxy-map/blob/main/src/data/factionSectors.json
const factionSectors = [
  {
    "factionName": "Alliance",
    "colour": "red",
    "sectors": [
      "Japrael",
      "Hapes Cluster",
      "Prackla",
      "Bothan Space",
      "Kwymar",
      "Nembus",
      "Gordian Reach",
      "Esstran",
      "Msst",
      "Sertar",
      "Perkell",
      "Ash Worlds",
      "Dominus",
      "Shadola",
      "Jubilar",
      "Phelleem",
      "Bryx",
      "Talcene",
      "Sarka",
      "Roche",
      "Taldot",
      "Lantillian",
      "Ghost Nebula",
      "Teraab",
      "Zeltros",
      "Esuain",
      "Trax",
      "Mytaranor",
      "Terr'skiar",
      "Kurost",
      "Lanic Space",
      "Lannic Wilds",
      "Dohlbani",
      "Endocray",
      "Manda",
      "Onatos",
      "Dufilvian",
      "Trans-Nebular",
      "Daimar",
      "Vendusii",
      "Garis",
      "Bon'nyuw-Luq",
      "Sanbra",
      "Juris",
      "Cadavine",
      "Woostri",
      "Vilonis",
      "Chommel",
      "Parnabe",
      "Ado",
      "Gorse",
      "Onderon",
      "Locris",
      "Hali",
      "Nojic",
      "Dona Laza",
      "Biivren",
      "Truum",
      "Sarka",
      "Hune",
      "Daalang",
      "Cyrillian Protectorate",
      "Circarpous",
      "Annecy",
      "Couronne",
      "Sloo",
      "Sevastol",
      "Noolian",
      "Aida",
      "Maerdocia",
      "Eclorar",
      "Hocatar",
      "Authala",
      "Tolemses",
      "Axion",
      "Oeiros",
      "Hangshan",
      "Askarian",
      "Nuon e Safyd",
      "Ombakond",
      "Inra-su-Mar",
      "Fel Hu",
      "Dimean",
      "Imberlin",
      "Sepan",
      "Hilo",
      "Surron",
      "Maladi",
      "Venzeiia",
      "Altier",
      "Kossa",
      "Harron",
      "Harron Marches",
      "Terathrace",
      "Belasco",
      "Noori",
      "Parcelus",
      "Spadja",
      "Lambda",
      "Herdessa",
      "Xan",
      "Yucrales",
      "Likasha",
      "Tandon",
      "Haserian",
      "Ividal",
      "Hertae",
      "I-Sector",
      "Nilgaard",
      "Colundra",
      "Pakuuni",
      "Calamari",
      "Centrality",
      "Brema",
      "Atravis",
      "Mayagil",
      "Subterrel",
      "Epsi Collective",
      "Hythrope",
      "Jurzan",
      "Yaraga",
      "Dustig",
      "Kira",
      "Tyus",
      "Iskin",
      "Far Xandil",
      "Mulgard",
      "Vish",
      "Bajic",
      "Kathol",
      "Minos",
      "Rseik",
      "Svivreni",
      "Khuiumin",
      "Tamarin",
      "Toblain",
      "Quence",
      "Parmel",
      "Sarin",
      "Hook Nebula",
      "Parmic",
      "Ryndellian",
      "Tarabba",
      "Airam",
      "Elrood",
      "Tantra",
      "Sluis",
      "Danjar",
      "Grumani",
      "Quess",
      "Alui",
      "Charra",
      "Treffani",
      "Thaere",
      "Eidoloni",
      "Var Hagen",
      "Steniplis",
      "Rolion",
      "Nuiri",
      "Thanium",
      "Vorzyd",
      "Lifh",
      "Maldrood",
      "Jospro",
      "Meridian",
      "Antemeridian",
      "Auril",
      "Belderone",
      "Keldrath",
      "Indrexu"
    ]
  },
  {
    "factionName": "Empire",
    "colour": "blue",
    "sectors": [
      "Seitia",
      "Saijo",
      "Rayter",
      "Kriz",
      "Dalicron",
      "Bruanii",
      "Videnda",
      "D'Aelgoth",
      "Jjannex",
      "Mektrun",
      "Senex",
      "Juvex",
      "Tungra",
      "Agarix",
      "Bozhnee",
      "Trailing Grant",
      "Cantons of Lahag",
      "Thand",
      "Jidlor Marches",
      "Marzoon",
      "Tashtor",
      "Halm",
      "Aldino",
      "Wazta",
      "Masla",
      "Gendius",
      "Irnaj",
      "Iska",
      "Wornal",
      "Piryn SHar",
      "Sombure",
      "Vensensor",
      "Hakartha",
      "Almak",
      "Elbaran",
      "Graador",
      "Narrant",
      "Oriolan",
      "Thuldin's Grant",
      "Mintitian Grant",
      "Extorin",
      "Great Agash",
      "Watza",
      "Givin Domain",
      "Boeus",
      "Drannik",
      "Corbett",
      "Trestis",
      "Stassia",
      "Dalqan",
      "Greater Plooriod",
      "Trans'Vulta",
      "Alland",
      "Lostar",
      "Corpheli",
      "Torranix",
      "Dolomar",
      "Galvoni",
      "Lytton",
      "Krenher",
      "Deadalis",
      "Sarla",
      "Ryborean",
      "Carvandir",
      "Qiilura",
      "Vadigult",
      "M'shinni",
      "Denevar",
      "Kiffu",
      "Ukatis",
      "Andirma",
      "Arc d'Stot",
      "Itopol",
      "Bes Ber Bikade",
      "Vulcusion",
      "Spirva",
      "Yushan",
      "Tregillis",
      "Rocantor",
      "Mbandamonte",
      "Brak",
      "Citlik",
      "Alchenaut",
      "Fennesa",
      "Trevura",
      "Chitarghar",
      "Har Worlds",
      "Semagi",
      "Takodana",
      "Dononter",
      "Stensen",
      "Zuma",
      "Trilon",
      "Pacanth Reach",
      "Moddell",
      "Bakura",
      "Bri'ahl",
      "Koradin",
      "Tunka",
      "Varada",
      "Kallea",
      "Wakeelmui",
      "Nara",
      "Shawken",
      "Borleias",
      "Ixtlar",
      "Farlax",
      "Vannell",
      "Tamban",
      "Aradia",
      "Thomork",
      "Illodia",
      "Abregado",
      "Jaso",
      "Tapani",
      "Herglic",
      "Botor Enclave",
      "Iphigin",
      "Gerrard",
      "Nemoidian",
      "Farrfin",
      "Atrisian Commonwealth",
      "Vulpter",
      "Alsaka",
      "Koros",
      "Zarracina",
      "Humbarine",
      "Rendili",
      "Corthenia",
      "Kuat",
      "Azure",
      "Bormea",
      "Darpa",
      "Demophon",
      "Foundry",
      "Immeria",
      "Trans-Jardeen",
      "Bestine",
      "Vatha",
      "Tomo-Reth",
      "Arkam",
      "Hevvrol",
      "Tacuni",
      "Brevost",
      "Druess",
      "Primtara",
      "Corweillian",
      "Shiwal",
      "Ojom",
      "Manoe",
      "Barsa",
      "Londori",
      "Dohu",
      "Tyan",
      "Chaarna",
      "Corellian",
      "Lettow",
      "Columus",
      "Parmorak",
      "Mezeg",
      "Homon",
      "Uquine",
      "Vorc",
      "Hollan",
      "Luuq",
      "Abaar",
      "Jalor",
      "Thory",
      "Belshar",
      "Tiala",
      "Bright Jewel",
      "Ploo",
      "Immalia",
      "Ehosiq",
      "Nicandra",
      "Ottega",
      "Fellwe",
      "O'pahz",
      "Pacor",
      "Clythe",
      "Neshei",
      "Hijoan Space",
      "Mandress",
      "Vardoss",
      "Fakir",
      "Reecee",
      "Outer Jalor",
      "Urce",
      "Hewett",
      "Strabin",
      "Noonian",
      "Halthor",
      "Fath",
      "Braxant",
      "Obtrexta",
      "Velcar",
      "Albarrio",
      "Prefsbelt",
      "Cassander",
      "Dantus",
      "Dynali",
      "Carrion",
      "Perinn",
      "Cademimu",
      "Oricho",
      "Corosi",
      "Weneen",
      "Meerian",
      "Ojoster",
      "Kordu",
      "Alderath",
      "Irishi",
      "Droma",
      "Kesh",
      "Atrivis",
      "Oplovis",
      "Lahara",
      "Tragan Cluster",
      "Ciutric",
      "Nijune",
      "Sprizen",
      "Morshdine",
      "Belsmuth",
      "Phateem",
      "Larrin",
      "Telerath",
      "Obroa-skai",
      "Alderaan",
      "Sarapin",
      "Barma",
      "Shelsha",
      "Haldeen",
      "Carida",
      "Belnar",
      "Baronos",
      "Kilbanis",
      "Resht",
      "Ator",
      "Dremulae",
      "Palawa",
      "Tepasi",
      "Parkis",
      "Quanta",
      "Hosnian",
      "Emmo",
      "Testarr",
      "Cuvacia",
      "Weemell",
      "Questal",
      "Khomm",
      "Kalist",
      "Deep Core Security Zone",
      "Galactic Center",
      "Odik",
      "Shwuy",
      "Omonoth",
      "Arkania",
      "Orus",
      "Anthos",
      "Mindor",
      "Champala",
      "Neshtab",
      "Ariarch",
      "Rago",
      "Churnis",
      "Dentari",
      "Zeemacht",
      "Adari",
      "Parfadi",
      "Motexx",
      "Duluur",
      "Teyr",
      "Sern",
      "Trunska",
      "Shasos",
      "Kanchen",
      "Kokash",
      "Callia",
      "Tynna",
      "Immerian Outback",
      "Athallia",
      "Mikaster",
      "Majoor",
      "Baroli",
      "Exodeen",
      "Quellor",
      "Morobe",
      "Gendrah-Narvin",
      "Tokamac",
      "Palamut",
      "Narvath",
      "Kailion",
      "Merthian",
      "Chaykin",
      "Churba",
      "Quelii",
      "Demetras",
      "Taanab",
      "Zaric",
      "Neshig",
      "Mokk",
      "Rachuk",
      "Iseno",
      "Hadar",
      "Bilbringi",
      "Corusca",
      "Tython",
      "Mandalore",
      "Doldur",
      "Javin",
      "Seswenna",
      "Spinward",
      "Dalonbian",
      "Veragi",
      "D'Astan",
      "Chopani",
      "Corva",
      "Meram",
      "Mieru'kar",
      "Kanz",
      "Relgim",
      "Raioballo",
      "Myto",
      "Clacis"
    ]
  },
  {
    "factionName": "Neutral/Hutt",
    "colour": "olive",
    "sectors": [
      "Hutt Space",
      "Kessel",
      "Bheriz",
      "Baxel",
      "Albanin",
      "Al-Nasrl",
      "Zoraster",
      "Galov",
      "Tammuz",
      "Quiberon",
      "Savareen",
      "Gaulus",
      "Arkanis"
    ]
  },
  {
    "factionName": "The Chiss Ascendancy",
    "colour": "cyan",
    "sectors": "Chiss Ascendancy"
  }
]
